apiVersion: v1
kind: Namespace
metadata:
  name: mcp-test-namespace

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-test-app
  namespace: mcp-test-namespace
  labels:
    app: mcp-test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mcp-test-app
  template:
    metadata:
      labels:
        app: mcp-test-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: mcp-test-service
  namespace: mcp-test-namespace
spec:
  selector:
    app: mcp-test-app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
