apiVersion: v1
kind: Namespace
metadata:
  name: mcp-test-namespace-2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-test-app-2
  namespace: mcp-test-namespace-2
  labels:
    app: mcp-test-app-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mcp-test-app-2
  template:
    metadata:
      labels:
        app: mcp-test-app-2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: mcp-test-service-2
  namespace: mcp-test-namespace-2
spec:
  selector:
    app: mcp-test-app-2
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
